version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-docker
    ports:
      - "33066:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - $PWD/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
    ports:
      - "33077:80"