version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-docker
    ports:
      - "33066:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - $PWD/data:/var/lib/mysql